### ISSUE TITLE
Final Fixes - Iteration 0 updates

### ISSUE THREAD

**Issue by Manuel192** [ManuehGitHub/ISO2-2023-A02#59]

**Comment by MiguelAruiz** [comment]
- Updated Use Case Diagrams so that they show only the Use Cases corresponding to the proper system. Changed colours to use cases on the server for each of the systems to be more distinguishable.
- Updated the list of requirements for the system, in order to maintain coherency with the current approach and the update on the Use Case Diagrams.
- The project's final cost section was outdated, still showing the previous approach with repeated requirements. A new screenshot has been uploaded
